#!/usr/bin/env python3

"""
server - A lightweight CLI tool to transfer files/folders to a remote server via SCP.
"""

import sys
import os

# Add the directory containing this script to the path
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
LIB_DIR = os.path.join(SCRIPT_DIR, "lib")
sys.path.insert(0, LIB_DIR)

from cli import run_cli

if __name__ == "__main__":
    run_cli()
